/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_characters__character_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arenas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Arenas */
        get: operations["list_arenas_arenas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arenas/{arena_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Arena */
        get: operations["get_arena_arenas__arena_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["google_login_auth_google_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/apple/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple Callback
         * @description Form-encoded callback from Apple after the user grants consent.
         *
         *     Apple posts `code`, `id_token` (JWT), and on the first login a JSON
         *     `user` blob. We exchange the code for tokens, verify the id_token
         *     against Apple's JWKS, then upsert the player and mint our own JWT.
         */
        post: operations["apple_callback_auth_apple_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Trade a refresh token for a fresh access + refresh pair.
         *
         *     The presented refresh JTI is consumed (single-use). Replays return 401.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/dev/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Start
         * @description Bypass draft and create a match directly. Useful for frontend dev.
         */
        post: operations["dev_start_match_dev_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_match_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_match__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Draft */
        post: operations["start_draft_draft_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_draft__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/{draft_id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Ban */
        post: operations["submit_ban_draft__draft_id__ban_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/{draft_id}/pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Pick */
        post: operations["submit_pick_draft__draft_id__pick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/{draft_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Draft */
        post: operations["finalize_draft_draft__draft_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/{draft_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Draft */
        post: operations["cancel_draft_draft__draft_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matchmaking/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join */
        post: operations["join_matchmaking_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matchmaking/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave */
        post: operations["leave_matchmaking_leave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unlocks/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_unlocks_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveStatus
         * @description A status currently applied to a character in-match.
         */
        ActiveStatus: {
            /** Name */
            name: string;
            /** Duration */
            duration: number;
            /**
             * Value
             * @default 0
             */
            value: number;
            /** Source */
            source?: string | null;
        };
        /**
         * Archetype
         * @enum {string}
         */
        Archetype: "damage_dealer" | "healer" | "tank" | "stunner" | "drainer" | "trickster" | "support" | "leader";
        /** Arena */
        Arena: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Modifiers */
            modifiers?: components["schemas"]["ArenaModifier"][];
        };
        /**
         * ArenaModifier
         * @description One global rule the arena imposes on the match.
         *
         *     The engine handles a known subset of `kind` values; unknown kinds are
         *     accepted and ignored so new arenas can be authored ahead of engine support.
         */
        ArenaModifier: {
            /** Kind */
            kind: string;
            /** Mythology */
            mythology?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * Value
             * @default 0
             */
            value: number;
            /**
             * Multiplier
             * @default 1
             */
            multiplier: number;
            essence?: components["schemas"]["Essence"] | null;
            /**
             * Target
             * @default all
             * @enum {string}
             */
            target: "all" | "side_a" | "side_b";
            damage_class?: components["schemas"]["DamageClass"] | null;
            skill_kind?: components["schemas"]["SkillKind"] | null;
            /**
             * Start Turn
             * @default 1
             */
            start_turn: number;
            /**
             * Every
             * @default 1
             */
            every: number;
        };
        /** BanPickBody */
        BanPickBody: {
            side: components["schemas"]["Side"];
            /** Character Id */
            character_id: string;
        };
        /** Character */
        Character: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Mythology */
            mythology: string;
            archetype: components["schemas"]["Archetype"];
            /** Base Hp */
            base_hp: number;
            /** Description */
            description?: string | null;
            /** Skills */
            skills: components["schemas"]["Skill"][];
        };
        /** CharacterState */
        CharacterState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Hp */
            hp: number;
            /** Hp Max */
            hp_max: number;
            /** Cooldowns */
            cooldowns?: {
                [key: string]: number;
            };
            /** Statuses */
            statuses?: components["schemas"]["ActiveStatus"][];
            /**
             * Shield
             * @default 0
             */
            shield: number;
            /** Shield Source */
            shield_source?: string | null;
            /** Granted Skills */
            granted_skills?: components["schemas"]["GrantedSkill"][];
            /** Last Skill Id */
            last_skill_id?: string | null;
        };
        /**
         * DamageClass
         * @enum {string}
         */
        DamageClass: "physical" | "magical" | "holy" | "mental";
        /** DevStartBody */
        DevStartBody: {
            /** Team A */
            team_a: string[];
            /** Team B */
            team_b: string[];
            /**
             * Arena Id
             * @default neutral
             */
            arena_id: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /**
         * DraftPhase
         * @enum {string}
         */
        DraftPhase: "arena_reveal" | "ban" | "pick" | "confirm" | "done" | "cancelled";
        /** DraftState */
        DraftState: {
            /** Draft Id */
            draft_id: string;
            /** Arena Id */
            arena_id: string;
            /** Side A Player Id */
            side_a_player_id: string;
            /** Side B Player Id */
            side_b_player_id: string;
            /** @default arena_reveal */
            phase: components["schemas"]["DraftPhase"];
            /** Bans */
            bans?: {
                [key: string]: string | null;
            };
            /** Picks */
            picks?: {
                [key: string]: string[];
            };
            /** Pick Order */
            pick_order?: components["schemas"]["Side"][];
            /**
             * Pick Index
             * @default 0
             */
            pick_index: number;
            /** Timer Deadline */
            timer_deadline?: string | null;
        };
        /**
         * Effect
         * @description One atomic effect applied when a skill resolves on a target.
         */
        Effect: {
            kind: components["schemas"]["EffectKind"];
            /**
             * Value
             * @default 0
             */
            value: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            damage_class?: components["schemas"]["DamageClass"] | null;
            /** Status */
            status?: string | null;
            /**
             * Piercing
             * @default false
             */
            piercing: boolean;
            /**
             * True
             * @default false
             */
            true: boolean;
        };
        /**
         * EffectKind
         * @enum {string}
         */
        EffectKind: "damage" | "heal" | "invulnerable" | "damage_reduction" | "damage_buff" | "destructible_shield" | "status" | "essence_drain" | "remove_afflictions" | "copy";
        /**
         * Essence
         * @description Energy resource for skills. Four colors plus a generic slot.
         * @enum {string}
         */
        Essence: "vigor" | "spirit" | "mind" | "blood" | "generic";
        /** FinalizeResponse */
        FinalizeResponse: {
            draft: components["schemas"]["DraftState"];
            /** Match Id */
            match_id: string;
        };
        /**
         * GrantedSkill
         * @description A skill borrowed from another character via the `copy` effect.
         *
         *     The copying character treats it as their own — paying its cost from
         *     their own essence pool, decrementing its cooldown alongside the rest,
         *     looking it up under the original `skill_id`. `source_character_id`
         *     points at the YAML the engine reads to find the actual `Skill` record.
         */
        GrantedSkill: {
            /** Skill Id */
            skill_id: string;
            /** Source Character Id */
            source_character_id: string;
            /** Turns Remaining */
            turns_remaining: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchRecord */
        MatchRecord: {
            /** Id */
            id: string;
            /** Arena Id */
            arena_id: string;
            /** Side A Player Id */
            side_a_player_id: string;
            /** Side B Player Id */
            side_b_player_id: string;
            /** Team A */
            team_a: string[];
            /** Team B */
            team_b: string[];
            /** Winner */
            winner: string | null;
            /** Turns */
            turns: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Ended At */
            ended_at?: string | null;
            /** Elo Delta A */
            elo_delta_a?: number | null;
            /** Elo Delta B */
            elo_delta_b?: number | null;
        };
        /** MatchState */
        MatchState: {
            /** Match Id */
            match_id: string;
            /**
             * Arena Id
             * @default neutral
             */
            arena_id: string;
            /**
             * Turn
             * @default 1
             */
            turn: number;
            /** @default A */
            current_side: components["schemas"]["Side"];
            a: components["schemas"]["PlayerState"];
            b: components["schemas"]["PlayerState"];
            /**
             * Rng Seed
             * @default 0
             */
            rng_seed: number;
            /**
             * Finished
             * @default false
             */
            finished: boolean;
            winner?: components["schemas"]["Side"] | null;
            /** Turn Deadline */
            turn_deadline?: string | null;
        };
        /**
         * MeResponse
         * @description Profile payload returned by `/auth/me`.
         *
         *     `player` is `None` when the JWT subject doesn't have a row in the players
         *     table — e.g. the local `/auth/dev-token` flow before the dev account has
         *     completed any sign-in.
         */
        MeResponse: {
            /** Sub */
            sub: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string | null;
            player?: components["schemas"]["Player"] | null;
        };
        /** Player */
        Player: {
            /** Id */
            id: string;
            /** Provider Subject */
            provider_subject: string;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Elo
             * @default 1000
             */
            elo: number;
            /** Unlocked Characters */
            unlocked_characters?: string[];
            /** Progress */
            progress?: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Last Seen */
            last_seen?: string | null;
        };
        /** PlayerState */
        PlayerState: {
            /** Id */
            id: string;
            side: components["schemas"]["Side"];
            /** Characters */
            characters: components["schemas"]["CharacterState"][];
            /** Essences */
            essences?: {
                [key: string]: number;
            };
        };
        /** QueueStatus */
        QueueStatus: {
            /** Queued */
            queued: boolean;
            /** Queue Size */
            queue_size: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Side
         * @enum {string}
         */
        Side: "A" | "B";
        /** Skill */
        Skill: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["SkillKind"];
            /** Cost */
            cost?: {
                [key: string]: number;
            };
            /**
             * Cooldown
             * @default 0
             */
            cooldown: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            target: components["schemas"]["TargetKind"];
            /** Effects */
            effects: components["schemas"]["Effect"][];
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * SkillKind
         * @enum {string}
         */
        SkillKind: "instant" | "ongoing" | "control";
        /** StartBody */
        StartBody: {
            /** Side A Player Id */
            side_a_player_id: string;
            /** Side B Player Id */
            side_b_player_id: string;
            /**
             * Arena Id
             * @default neutral
             */
            arena_id: string;
        };
        /** StartedMatch */
        StartedMatch: {
            /** Match Id */
            match_id: string;
            state: components["schemas"]["MatchState"];
        };
        /**
         * TargetKind
         * @enum {string}
         */
        TargetKind: "single_enemy" | "all_enemies" | "single_ally" | "all_allies" | "self";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token?: string | null;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /** UnlockRulePayload */
        UnlockRulePayload: {
            /** Character Id */
            character_id: string;
            /** Description */
            description: string;
            /** Progress Key */
            progress_key: string | null;
            /** Target */
            target: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_characters_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
        };
    };
    get_character_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_arenas_arenas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Arena"][];
                };
            };
        };
    };
    get_arena_arenas__arena_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arena_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Arena"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_auth_google_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    apple_callback_auth_apple_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    dev_start_match_dev_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevStartBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartedMatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_match_history_get: {
        parameters: {
            query?: {
                player_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_match__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_draft_draft_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_draft__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ban_draft__draft_id__ban_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanPickBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_pick_draft__draft_id__pick_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanPickBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_draft_draft__draft_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_draft_draft__draft_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_matchmaking_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueStatus"];
                };
            };
        };
    };
    leave_matchmaking_leave_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueStatus"];
                };
            };
        };
    };
    list_rules_unlocks_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlockRulePayload"][];
                };
            };
        };
    };
}
